# Generated by Django 4.2.2 on 2023-06-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sanskrit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='telugu',
            field=models.IntegerField(default=0),
        ),
    ]
